# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TallyTransport
email: willpdfs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site hosting information about transportation and traffic issues in Tallahassee, Florida.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whanley.github.io/TallyTransport" # the base hostname & protocol for your site
twitter: HanleyWill
teaser: CapCirc_Centerville.JPG

# Build settings
markdown: kramdown
